# Generated by Django 2.2 on 2020-10-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='token',
            new_name='tokenno',
        ),
    ]
